ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMP;

UPDATE orders
SET delivered_at = created_at
WHERE status = 'DELIVERED'
  AND delivered_at IS NULL;

CREATE TABLE IF NOT EXISTS return_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    status VARCHAR(32) NOT NULL,
    admin_note VARCHAR(1000),
    requested_at TIMESTAMP NOT NULL,
    reviewed_at TIMESTAMP,
    completed_at TIMESTAMP,
    CONSTRAINT return_requests_order_fk
        FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT return_requests_status_check
        CHECK (status IN ('REQUESTED', 'APPROVED', 'REJECTED', 'COMPLETED'))
);

CREATE INDEX IF NOT EXISTS return_requests_status_requested_at_idx
    ON return_requests (status, requested_at DESC);
