create table if not exists order_status_history (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    status varchar(32) not null,
    changed_at timestamp not null,
    constraint order_status_history_order_fk
        foreign key (order_id) references orders (id) on delete cascade,
    constraint order_status_history_status_check
        check (status in ('PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED'))
);

create index if not exists order_status_history_order_changed_at_idx
    on order_status_history (order_id, changed_at);

insert into order_status_history (order_id, status, changed_at)
select id, status, coalesce(delivered_at, shipped_at, created_at)
from orders
where not exists (
    select 1
    from order_status_history history
    where history.order_id = orders.id
);
