server:
  port: ${COMMERCE_SERVICE_PORT:8082}

spring:
  application:
    name: commerce-service

  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
      - optional:file:../../.env[.properties]

  datasource:
    url: ${COMMERCE_DB_URL:${DB_URL}}
    username: ${COMMERCE_DB_USERNAME:${DB_USERNAME}}
    password: ${COMMERCE_DB_PASSWORD:${DB_PASSWORD}}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ${COMMERCE_DB_SCHEMA:commerce}
        hbm2ddl:
          create_namespaces: true
